# Generated by Django 5.1.6 on 2025-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=50)),
                ('grade1', models.IntegerField()),
                ('grade2', models.IntegerField()),
                ('grade3', models.IntegerField()),
                ('grade4', models.IntegerField()),
                ('grade5', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Список студентів',
            },
        ),
    ]
