# Generated by Django 5.1.6 on 2025-05-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_list',
            name='scholarship',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
